name: Selenium Docker CI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: selenium-base

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout
      - name: Checkout code
        uses: actions/checkout@v4

      # 2️⃣ Set build date
      - name: Set build date
        run: echo "BUILD_DATE=$(date +%Y-%m-%d)" >> $GITHUB_ENV
      # 2️⃣ Valid
      - name: Debug secrets
        run: |
          echo "User exists"
          if [ -z "${{ secrets.DOCKERHUB_TOKEN }}" ]; then
            echo "Password is EMPTY"
            exit 1
          fi

      # 3️⃣ Login DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }} \
            -f docker/Dockerfile .

      # 5️⃣ Run Selenium tests
      - name: Run Selenium tests
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:v2.0.0 \
            pytest

      # 6️⃣ Push image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.BUILD_DATE }}
